version: 0.2

phases:
  build:
    commands:
      - echo "Hello"
      - aws --version
      - aws s3 cp ${PROJECT_S3_ZIP} project.zip
      - unzip project.zip
      - ls -lh
      - cd ${PROJECT_NAME}
      - ./gradlew build
      - cd build/generated-sdk/typescript
      - npm install
      - npm run build
      - cp package.json dist/
      - cd dist
      - aws codeartifact login --tool npm --repository ${CODEARTIFACT_REPOSITORY} --domain ${CODEARTIFACT_DOMAIN} --domain-owner ${CODEARTIFACT_OWNER} --region ${CODEARTIFACT_REGION}
      - npm publish
